name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm ci
      - run: npm run check

      - name: Execução de Testes
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          STRING_VARIABLE_TEST: ${{ vars.STRING_VARIABLE_TEST }}
          NUMERIC_VARIABLE_TEST: ${{ vars.NUMERIC_VARIABLE_TEST }}
          BOOLEAN_VARIABLE_TEST: ${{ vars.BOOLEAN_VARIABLE_TEST }}
        run: npm test
